const pageData = {
    background_path: "https://qnm.hunliji.com/o_1d5mf66m1femghpcrs5dds5i13.jpg",
    music: {
        audio: "http://qnvideo.hunliji.com/o_1bs08l4p6qohmjtupi66b10bd9.mp3",
        close_img: "http://qnm.hunliji.com/o_1br8kc3teajn609b0peckg5g13.png",
        img: "http://qnm.hunliji.com/o_1br8kc0amgei16441m8bnckahru.png"
    },
    page_icon: "",
    theme_background: "https://qnm.hunliji.com/o_1d5mf66m1femghpcrs5dds5i13.jpg",
    page: [
        {
            layout: {
                background: "http://qnm.hunliji.com/o_1br87o6jh14cf2s6i6j1k3to5k1v.jpg",
                elements: [
                    {
                        animate:["rotateInDownRight"],
                        delay: ["1500ms"],
                        duration: ["2000ms"],
                        height: "112",
                        id: "ele_0",
                        img: "http://qnm.hunliji.com/o_1br87qsthd1h1rd5l1413cp16pd3q.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "133",
                        x: "29",
                        y: "397",
                        z_order: "1"
                    },
                    {
                        animate: ["rotateInDownRight"],
                        delay: ["1500ms"],
                        duration: ["2000ms"],
                        height: "239",
                        id: "ele_1",
                        img: "http://qnm.hunliji.com/o_1br87qv2qfukbit6a01slf1hqc3v.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "192",
                        x: "53",
                        y: "289",
                        z_order: "2"
                    },
                    {
                        animate: ["rotateInDownRight"],
                        delay: ["1500ms"],
                        duration: ["2000ms"],
                        height: "244",
                        id: "ele_2",
                        img: "http://qnm.hunliji.com/o_1br87r1ppo8h19na1hcn16oe1s4u44.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "282",
                        x: "99",
                        y: "139",
                        z_order: "1"
                    },
                    {
                        animate: ["rotateInDownRight"],
                        delay: ["1500ms"],
                        duration: ["2000ms"],
                        height: "225",
                        id: "ele_3",
                        img: "http://qnm.hunliji.com/o_1br87r4go687df712il19211h9t49.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "149",
                        x: "225",
                        y: "82",
                        z_order: "1"
                    },
                    {
                        animate: ["fadeInUp"],
                        delay: ["1500ms"],
                        duration: ["2000ms"],
                        height: "139",
                        id: "ele_4",
                        img: "http://qnm.hunliji.com/o_1br87r84pvva1eqota81f8j18jo4e.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "188",
                        x: "357",
                        y: "73",
                        z_order: "2"
                    },
                    {
                        animate: ["zoomIn"],
                        delay: ["1500ms"],
                        duration: ["2000ms"],
                        height: "249",
                        id: "ele_5",
                        img: "http://qnm.hunliji.com/o_1br87rb98cnt1p98ki6j4r125p4j.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "281",
                        x: "440",
                        y: "152",
                        z_order: "1"
                    },
                    {
                        animate: ["zoomIn"],
                        delay: ["1500ms"],
                        duration: ["2000ms"],
                        height: "242",
                        id: "ele_6",
                        img: "http://qnm.hunliji.com/o_1br87rid6cqi1d5n1aoa138j15go56.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "272",
                        x: "64",
                        y: "885",
                        z_order: "1"
                    },
                    {
                        animate: ["fadeInDown"],
                        delay: ["1500ms"],
                        duration: ["2000ms"],
                        height: "121",
                        id: "ele_7",
                        img: "http://qnm.hunliji.com/o_1br87rkra1an3qec1slt1usb10v45b.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "163",
                        x: "336",
                        y: "1011",
                        z_order: "1"
                    },
                    {
                        animate: ["zoomIn"],
                        delay: ["1500ms"],
                        duration: ["2000ms"],
                        height: "212",
                        id: "ele_8",
                        img: "http://qnm.hunliji.com/o_1br87rn4r1ke5q351or210q1vr35g.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "209",
                        x: "484",
                        y: "875",
                        z_order: "1"
                    },
                    {
                        animate: ["fadeIn"],
                        delay: ["100ms"],
                        duration: ["2000ms"],
                        height: "931",
                        id: "ele_9",
                        img: "http://qnm.hunliji.com/o_1br884v5ji4e17hb17c51h1q1pes6a.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "657",
                        x: "50",
                        y: "142",
                        z_order: "3"
                    },
                    {
                        animate: ["fadeInDown"],
                        delay: ["100ms"],
                        duration: ["2000ms"],
                        height: "931",
                        id: "ele_10",
                        img: "http://qnm.hunliji.com/o_1br886klbojb78rulu1mr512l6f.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "599",
                        x: "84",
                        y: "142",
                        z_order: "4"
                    },
                    {
                        animate: ["fadeInUp"],
                        delay: ["100ms"],
                        duration: ["2000ms"],
                        height: "823",
                        id: "ele_11",
                        img: "http://qnm.hunliji.com/o_1br886mu89fo1ab7cfscj2ha36k.png",
                        inf_delay: "0ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "657",
                        x: "50",
                        y: "184",
                        z_order: "5"
                    },
                    {
                        animate: ["fadeIn"],
                        delay: ["1000ms"],
                        duration: ["2000ms"],
                        height: "132",
                        id: "ele_12",
                        img: "http://qnm.hunliji.com/o_1br888hvgel11ul08kpv6e14kk77.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "417",
                        x: "186",
                        y: "308",
                        z_order: "4"
                    },
                    {
                        animate: ["fadeIn"],
                        delay: ["2000ms"],
                        duration: ["2000ms"],
                        height: "72",
                        id: "ele_13",
                        img: "http://qnm.hunliji.com/o_1br888k9h1h31l881jf416m6tqh7c.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "197",
                        x: "277",
                        y: "556",
                        z_order: "4"
                    },
                    {
                        animate: ["fadeIn"],
                        delay: ["1500ms"],
                        duration: ["2000ms"],
                        edit_btn_position: 0,
                        height: "56",
                        id: 13012,
                        img: "http://qnm.hunliji.com/FhzyYmcnEIIdNIhFZKSMLFMcVjYG",
                        inf_delay: "",
                        inf_duration: "",
                        infinite: "",
                        is_down: 0,
                        is_scale: 0,
                        rotate: "0",
                        text_type: "groom",
                        type: "text",
                        width: "527",
                        x: "112",
                        y: "474",
                        z_order: "4"
                    },
                    {
                        animate: ["fadeIn"],
                        delay: ["2500ms"],
                        duration: ["2000ms"],
                        edit_btn_position: 0,
                        height: "56",
                        id: 13013,
                        img: "http://qnm.hunliji.com/Fq7dNDvfbKpO1YUsIWuhE4fsJA6_",
                        inf_delay: "",
                        inf_duration: "",
                        infinite: "",
                        is_down: 0,
                        is_scale: 0,
                        rotate: "0",
                        text_type: "bride",
                        type: "text",
                        width: "527",
                        x: "112",
                        y: "667",
                        z_order: "4"
                    },
                    {
                        animate: ["fadeIn"],
                        delay: ["3000ms"],
                        duration: ["2000ms"],
                        edit_btn_position: 0,
                        height: "37",
                        id: 13014,
                        img: "http://qnm.hunliji.com/FrQFlOgwvjs82J262tzsPJlZ3tFJ",
                        inf_delay: "",
                        inf_duration: "",
                        infinite: "",
                        is_down: 0,
                        is_scale: 0,
                        rotate: "0",
                        text_type: "time",
                        type: "text",
                        width: "426",
                        x: "163",
                        y: "784",
                        z_order: "4"
                    },
                    {
                        animate: ["fadeIn"],
                        delay: ["3000ms"],
                        duration: ["2000ms"],
                        edit_btn_position: 0,
                        height: "73",
                        id: 13015,
                        img: "http://qnm.hunliji.com/FgVKAQSfKPUxqHILjA11lS7h0H_7",
                        inf_delay: "",
                        inf_duration: "",
                        infinite: "",
                        is_down: 0,
                        is_scale: 0,
                        rotate: "0",
                        text_type: "location",
                        type: "text",
                        width: "391",
                        x: "180",
                        y: "835",
                        z_order: "4"
                    }
                ]
            }
        },
        {
            layout:{
                background: "http://qnm.hunliji.com/o_1br88mbad1g2q1l237ut1dsherl8b.jpg",
                elements: [
                    {
                        animate: ["zoomIn"],
                        delay: ["1000ms"],
                        duration: ["2000ms"],
                        height: "137",
                        id: "ele_0",
                        img: "http://qnm.hunliji.com/o_1br88n53ovtnjaoka0fgi6el9h.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "132",
                        x: "14",
                        y: "20",
                        z_order: "2"
                    },
                    {
                        animate: ["rotateInDownLeft"],
                        delay: ["1500ms"],
                        duration: ["2000ms"],
                        height: "147",
                        id: "ele_1",
                        img: "http://qnm.hunliji.com/o_1br88n73q11gkmnumgm1ebv1he79m.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "138",
                        x: "582",
                        y: "846",
                        z_order: "2"
                    },
                    {
                        animate: ["rotateInDownRight"],
                        delay: ["1500ms"],
                        duration: ["2000ms"],
                        height: "160",
                        id: "ele_2",
                        img: "http://qnm.hunliji.com/o_1br88n9mto271q0ra2u1a0esaga2.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "147",
                        x: "52",
                        y: "999",
                        z_order: "2"
                    },
                    {
                        animate: ["fadeIn"],
                        delay: ["2000ms"],
                        duration: ["2000ms"],
                        height: "23",
                        id: "ele_3",
                        img: "http://qnm.hunliji.com/o_1br88ne1t16n34us15l81tuk15jmae.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "334",
                        x: "208",
                        y: "1022",
                        z_order: "2"
                    },
                    {
                        animate: ["fadeIn"],
                        delay: ["2000ms"],
                        duration: ["2000ms"],
                        height: "30",
                        id: "ele_4",
                        img: "http://qnm.hunliji.com/o_1br88nhc868a5etr0l1ne5ilpaq.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "263",
                        x: "243",
                        y: "1080",
                        z_order: "2"
                    },
                    {
                        animate: ["zoomIn"],
                        delay: ["2000ms"],
                        duration: ["2000ms"],
                        height: "4",
                        id: "ele_5",
                        img: "http://qnm.hunliji.com/o_1br88nk0mgag1vd91dfh13hq1djob6.png",
                        inf_delay: "ms",
                        inf_duration: "ms",
                        infinite: "",
                        is_down: "0",
                        is_scale: "0",
                        line_spacing: null,
                        rotate: "",
                        width: "124",
                        x: "313",
                        y: "1125",
                        z_order: "2"
                    },
                    {
                        animate: ["fadeInDown"],
                        delay: ["100ms"],
                        duration: ["2000ms"],
                        edit_btn_position: 0,
                        fit_full_screen: 0,
                        height: "851",
                        id: 9439,
                        img: "http://qnm.hunliji.com/o_1br8938ne17ai2os8joo1k1kjpbg.jpg",
                        inf_delay: "",
                        inf_duration: "",
                        infinite: "",
                        is_down: 0,
                        is_scale: 0,
                        mask: {img: "http://qnm.hunliji.com/o_1br88no0p1fl91nus1517j37gf0bb.png", width: "628", height: "851"},
                        rotate: 0,
                        type: "image",
                        width: "628",
                        x: "61",
                        y: "77",
                        z_order: 1
                    }
                ]
            }
        },
        {

        }
    ]
}