const pageData = {
    "page":
        [
            {
            "layout": {
                "background": "../static/images/pageBg.jpg",
                "elements": [
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rotateInDownRight"],
                    "delay": ["1500ms"],
                    "height": "112",
                    "img": "../static/images/page1/elementImg1.png",
                    "rotate": "",
                    "width": "133",
                    "x": "29",
                    "y": "397",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_0",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rotateInDownRight"],
                    "delay": ["1500ms"],
                    "height": "239",
                    "img": "../static/images/page1/elementImg2.png",
                    "rotate": "",
                    "width": "192",
                    "x": "53",
                    "y": "289",
                    "z_order": "2",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_1",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rotateInDownRight"],
                    "delay": ["1500ms"],
                    "height": "244",
                    "img": "../static/images/page1/elementImg3.png",
                    "rotate": "",
                    "width": "282",
                    "x": "99",
                    "y": "139",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_2",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rotateInDownRight"],
                    "delay": ["1500ms"],
                    "height": "225",
                    "img": "../static/images/page1/elementImg4.png",
                    "rotate": "",
                    "width": "149",
                    "x": "225",
                    "y": "82",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_3",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeInUp"],
                    "delay": ["1500ms"],
                    "height": "139",
                    "img": "../static/images/page1/elementImg5.png",
                    "rotate": "",
                    "width": "188",
                    "x": "357",
                    "y": "73",
                    "z_order": "2",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_4",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["1500ms"],
                    "height": "249",
                    "img": "../static/images/page1/elementImg6.png",
                    "rotate": "",
                    "width": "281",
                    "x": "440",
                    "y": "152",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_5",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["1500ms"],
                    "height": "242",
                    "img": "../static/images/page1/elementImg7.png",
                    "rotate": "",
                    "width": "272",
                    "x": "64",
                    "y": "885",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_6",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeInDown"],
                    "delay": ["1500ms"],
                    "height": "121",
                    "img": "../static/images/page1/elementImg8.png",
                    "rotate": "",
                    "width": "163",
                    "x": "336",
                    "y": "1011",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_7",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["1500ms"],
                    "height": "212",
                    "img": "../static/images/page1/elementImg9.png",
                    "rotate": "",
                    "width": "209",
                    "x": "484",
                    "y": "875",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_8",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["100ms"],
                    "height": "931",
                    "img": "../static/images/page1/elementImg10.png",
                    "rotate": "",
                    "width": "657",
                    "x": "50",
                    "y": "142",
                    "z_order": "3",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_9",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeInDown"],
                    "delay": ["100ms"],
                    "height": "931",
                    "img": "../static/images/page1/elementImg11.png",
                    "rotate": "",
                    "width": "599",
                    "x": "84",
                    "y": "142",
                    "z_order": "4",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_10",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "0ms",
                    "inf_duration": "ms",
                    "animate": ["fadeInUp"],
                    "delay": ["100ms"],
                    "height": "823",
                    "img": "../static/images/page1/elementImg12.png",
                    "rotate": "",
                    "width": "657",
                    "x": "50",
                    "y": "184",
                    "z_order": "5",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_11",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["1000ms"],
                    "height": "132",
                    "img": "./image/page1/titleTextImg.png",
                    "rotate": "",
                    "width": "417",
                    "x": "186",
                    "y": "308",
                    "z_order": "4",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_12",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["2000ms"],
                    "height": "72",
                    "img": "./image/page1/titleTextImg2.png",
                    "rotate": "",
                    "width": "197",
                    "x": "277",
                    "y": "556",
                    "z_order": "4",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_13",
                    "line_spacing": null
                },
                    {
                    "animate": ["fadeIn"],
                    "img": "./image/page1/menNameImg.png",
                    "delay": ["1500"],
                    "rotate": "0",
                    "x": "112",
                    "y": "474",
                    "width": "527",
                    "height": "56",
                    "z_order": "4",
                    "id": 13012,
                    "type": "text",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "text_type": "groom",
                    "edit_btn_position": 0
                },
                    {
                    "animate": ["fadeIn"],
                    "img": "./image/page1/womenNameImg.png",
                    "delay": ["2500"],
                    "rotate": "0",
                    "x": "112",
                    "y": "667",
                    "width": "527",
                    "height": "56",
                    "z_order": "4",
                    "id": 13013,
                    "type": "text",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "text_type": "bride",
                    "edit_btn_position": 0
                },
                    {
                    "animate": ["fadeIn"],
                    "img": "./image/page1/dateImg.png",
                    "delay": ["3000"],
                    "rotate": "0",
                    "x": "163",
                    "y": "784",
                    "width": "426",
                    "height": "37",
                    "z_order": "4",
                    "id": 13014,
                    "type": "text",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "text_type": "time",
                    "edit_btn_position": 0
                },
                    {
                    "animate": ["fadeIn"],
                    "img": "./image/page1/addressImg.png",
                    "delay": ["3000"],
                    "rotate": "0",
                    "x": "180",
                    "y": "835",
                    "width": "391",
                    "height": "73",
                    "z_order": "4",
                    "id": 13015,
                    "type": "text",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "text_type": "location",
                    "edit_btn_position": 0
                }
                ]
            }
        },
            {
            "layout": {
                "background": "../static/images/pageBg.jpg",
                "elements": [
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["1000ms"],
                    "height": "137",
                    "img": "../static/images/page2/elementImg1.png",
                    "rotate": "",
                    "width": "132",
                    "x": "14",
                    "y": "20",
                    "z_order": "2",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_0",
                    "line_spacing": null
                    },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rotateInDownLeft"],
                    "delay": ["1500ms"],
                    "height": "147",
                    "img": "../static/images/page2/elementImg2.png",
                    "rotate": "",
                    "width": "138",
                    "x": "582",
                    "y": "846",
                    "z_order": "2",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_1",
                    "line_spacing": null
                    },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rotateInDownRight"],
                    "delay": ["1500ms"],
                    "height": "160",
                    "img": "../static/images/page2/elementImg3.png",
                    "rotate": "",
                    "width": "147",
                    "x": "52",
                    "y": "999",
                    "z_order": "2",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_2",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["2000ms"],
                    "height": "23",
                    "img": "./image/page2/textImg1.png",
                    "rotate": "",
                    "width": "334",
                    "x": "208",
                    "y": "1022",
                    "z_order": "2",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_3",
                    "line_spacing": null
                    },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["2000ms"],
                    "height": "30",
                    "img": "./image/page2/textImg2.png",
                    "rotate": "",
                    "width": "263",
                    "x": "243",
                    "y": "1080",
                    "z_order": "2",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_4",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["2000ms"],
                    "height": "4",
                    "img": "./image/page2/lineImg.png",
                    "rotate": "",
                    "width": "124",
                    "x": "313",
                    "y": "1125",
                    "z_order": "2",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_5",
                    "line_spacing": null
                },
                    {
                    "animate": ["fadeInDown"],
                    "img": "./image/page2/peopleImg.jpg",
                    "delay": ["100"],
                    "rotate": 0,
                    "x": "61",
                    "y": "77",
                    "width": "628",
                    "height": "851",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "628",
                        "height": "851"
                    },
                    "z_order": 1,
                    "id": 9439,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                }
                ]
            }
        },
            {
            "layout": {
                "background": "../static/images/pageBg.jpg",
                "elements": [
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["1000ms"],
                    "height": "142",
                    "img": "../static/images/page3/elementImg1.png",
                    "rotate": "",
                    "width": "134",
                    "x": "27",
                    "y": "40",
                    "z_order": "3",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_0",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeInDown"],
                    "delay": ["1500ms"],
                    "height": "208",
                    "img": "../static/images/page3/elementImg2.png",
                    "rotate": "",
                    "width": "172",
                    "x": "503",
                    "y": "409",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_1",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["1000ms"],
                    "height": "154",
                    "img": "../static/images/page3/elementImg3.png",
                    "rotate": "",
                    "width": "126",
                    "x": "520",
                    "y": "715",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_2",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["1500ms"],
                    "height": "23",
                    "img": "./image/page3/textImg1.png",
                    "rotate": "",
                    "width": "193",
                    "x": "484",
                    "y": "890",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_3",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rollIn"],
                    "delay": ["2000ms"],
                    "height": "93",
                    "img": "./image/page3/textImg2.png",
                    "rotate": "",
                    "width": "93",
                    "x": "571",
                    "y": "1018",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_4",
                    "line_spacing": null
                },
                    {
                    "animate": ["fadeInRight"],
                    "img": "./image/page3/peopleImg1.jpg",
                    "delay": ["100"],
                    "rotate": 0,
                    "x": "61",
                    "y": "77",
                    "width": "628",
                    "height": "393",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "628",
                        "height": "393"
                    },
                    "z_order": 2,
                    "id": 9486,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["3000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                },
                    {
                    "animate": ["fadeInLeft"],
                    "img": "./image/page3/peopleImg2.jpg",
                    "delay": ["100"],
                    "rotate": 0,
                    "x": "61",
                    "y": "513",
                    "width": "386",
                    "height": "629",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "386",
                        "height": "629"
                    },
                    "z_order": 1,
                    "id": 9487,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["3000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                }
                ]
            }
        },
            {
            "layout": {
                "background": "../static/images/pageBg.jpg",
                "elements": [
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["3000ms"],
                    "height": "310",
                    "img": "../static/images/page4/elementImg1.png",
                    "rotate": "",
                    "width": "175",
                    "x": "311",
                    "y": "236",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_0",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["1500ms"],
                    "height": "75",
                    "img": "../static/images/page4/elementImg2.png",
                    "rotate": "",
                    "width": "115",
                    "x": "318",
                    "y": "594",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_1",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rotateInDownRight"],
                    "delay": ["1500ms"],
                    "height": "188",
                    "img": "../static/images/page4/elementImg3.png",
                    "rotate": "",
                    "width": "171",
                    "x": "608",
                    "y": "397",
                    "z_order": "3",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_2",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["2000ms"],
                    "height": "23",
                    "img": "./image/page4/textImg1.png",
                    "rotate": "",
                    "width": "354",
                    "x": "198",
                    "y": "688",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_3",
                    "line_spacing": null
                },
                    {
                    "animate": ["fadeInLeft"],
                    "img": "./image/page4/peopleImg1.jpg",
                    "delay": ["100"],
                    "rotate": 0,
                    "x": "61",
                    "y": "77",
                    "width": "330",
                    "height": "485",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "330",
                        "height": "485"
                    },
                    "z_order": 1,
                    "id": 9610,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                },
                    {
                    "animate": ["zoomIn"],
                    "img": "./image/page4/peopleImg2.jpg",
                    "delay": ["1000"],
                    "rotate": 0,
                    "x": "438",
                    "y": "149",
                    "width": "251",
                    "height": "326",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "251",
                        "height": "326"
                    },
                    "z_order": 2,
                    "id": 9611,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["3000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                },
                    {
                    "animate": ["fadeIn"],
                    "img": "./image/page4/peopleImg3.jpg",
                    "delay": ["2500"],
                    "rotate": 0,
                    "x": "61",
                    "y": "757",
                    "width": "628",
                    "height": "386",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "628",
                        "height": "386"
                    },
                    "z_order": 1,
                    "id": 9612,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                }
                ]
            }
        },
            {
            "layout": {
                "background": "../static/images/pageBg.jpg",
                "elements": [
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rotateInDownRight"],
                    "delay": ["100ms"],
                    "height": "111",
                    "img": "../static/images/page5/elementImg1.png",
                    "rotate": "",
                    "width": "147",
                    "x": "284",
                    "y": "71",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_0",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["500ms"],
                    "height": "23",
                    "img": "./image/page5/textImg1.png",
                    "rotate": "",
                    "width": "285",
                    "x": "232",
                    "y": "200",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_1",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["500ms"],
                    "height": "4",
                    "img": "./image/page5/lineImg1.png",
                    "rotate": "",
                    "width": "112",
                    "x": "319",
                    "y": "246",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_2",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeInLeft"],
                    "delay": ["1500ms"],
                    "height": "177",
                    "img": "../static/images/page5/elementImg2.png",
                    "rotate": "",
                    "width": "158",
                    "x": "-25",
                    "y": "857",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_3",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["1500ms"],
                    "height": "192",
                    "img": "../static/images/page5/elementImg3.png",
                    "rotate": "",
                    "width": "185",
                    "x": "615",
                    "y": "959",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_4",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["2000ms"],
                    "height": "72",
                    "img": "./image/page5/textImg2.png",
                    "rotate": "",
                    "width": "300",
                    "x": "225",
                    "y": "928",
                    "z_order": "1",
                    "duration": ["3000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_5",
                    "line_spacing": null
                },
                    {
                    "animate": ["fadeInLeft"],
                    "img": "./image/page5/peopleImg1.jpg",
                    "delay": ["1000"],
                    "rotate": 0,
                    "x": "55",
                    "y": "295",
                    "width": "640",
                    "height": "516",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "640",
                        "height": "516"
                    },
                    "z_order": 1,
                    "id": 9670,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["3000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                }
                ]
            }
        },
            {
            "layout": {
                "background": "../static/images/pageBg.jpg",
                "elements": [
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeInLeft"],
                    "delay": ["1000ms"],
                    "height": "126",
                    "img": "../static/images/page6/elementImg1.png",
                    "rotate": "",
                    "width": "262",
                    "x": "-44",
                    "y": "24",
                    "z_order": "2",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_0",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rotateInDownRight"],
                    "delay": ["2000ms"],
                    "height": "190",
                    "img": "../static/images/page6/elementImg2.png",
                    "rotate": "",
                    "width": "152",
                    "x": "526",
                    "y": "1060",
                    "z_order": "2",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_1",
                    "line_spacing": null
                },
                    {
                    "animate": ["fadeInDown"],
                    "img": "./image/page6/peopleImg1.jpg",
                    "delay": ["100"],
                    "rotate": 0,
                    "x": "61",
                    "y": "77",
                    "width": "628",
                    "height": "1066",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "628",
                        "height": "1066"
                    },
                    "z_order": 1,
                    "id": 9545,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["3000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                }
                ]
            }
        },
            {
            "layout": {
                "background": "../static/images/pageBg.jpg",
                "elements": [
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["1000ms"],
                    "height": "115",
                    "img": "../static/images/page7/elementImg1.png",
                    "rotate": "",
                    "width": "134",
                    "x": "19",
                    "y": "38",
                    "z_order": "2",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_0",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rotateInDownRight"],
                    "delay": ["1500ms"],
                    "height": "248",
                    "img": "../static/images/page7/elementImg2.png",
                    "rotate": "",
                    "width": "226",
                    "x": "452",
                    "y": "907",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_1",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["1000ms"],
                    "height": "4",
                    "img": "./image/page7/lineImg1.png",
                    "rotate": "",
                    "width": "88",
                    "x": "87",
                    "y": "926",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_2",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeInUp"],
                    "delay": ["1500ms"],
                    "height": "26",
                    "img": "./image/page7/textImg1.png",
                    "rotate": "",
                    "width": "296",
                    "x": "85",
                    "y": "964",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_3",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeInUp"],
                    "delay": ["2000ms"],
                    "height": "30",
                    "img": "./image/page7/textImg2.png",
                    "rotate": "",
                    "width": "117",
                    "x": "87",
                    "y": "1010",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_4",
                    "line_spacing": null
                },
                    {
                    "animate": ["fadeInLeft"],
                    "img": "./image/page7/peopleImg1.jpg",
                    "delay": ["100"],
                    "rotate": 0,
                    "x": "61",
                    "y": "77",
                    "width": "628",
                    "height": "389",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "628",
                        "height": "389"
                    },
                    "z_order": 1,
                    "id": 9546,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["3000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                },
                    {
                    "animate": ["fadeInRight"],
                    "img": "./image/page7/peopleImg2.jpg",
                    "delay": ["100"],
                    "rotate": 0,
                    "x": "61",
                    "y": "466",
                    "width": "628",
                    "height": "389",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "628",
                        "height": "389"
                    },
                    "z_order": 1,
                    "id": 9547,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["3000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                }
                ]
            }
        },
            {
            "layout": {
                "background": "../static/images/pageBg.jpg",
                "elements": [
                    {
                    "infinite": "",
                    "inf_delay": "",
                    "inf_duration": "",
                    "animate": ["fadeInDown"],
                    "delay": ["3000"],
                    "height": "223",
                    "img": "../static/images/page8/elementImg1.png",
                    "rotate": "",
                    "width": "156",
                    "x": "2",
                    "y": "-33",
                    "z_order": "2",
                    "duration": ["2000"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_0",
                    "line_spacing": ""
                },
                    {
                    "infinite": "",
                    "inf_delay": "",
                    "inf_duration": "",
                    "animate": ["rotateInDownRight"],
                    "delay": ["2000"],
                    "height": "195",
                    "img": "../static/images/page8/elementImg2.png",
                    "rotate": "",
                    "width": "180",
                    "x": "600",
                    "y": "811",
                    "z_order": "2",
                    "duration": ["2000"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_1",
                    "line_spacing": ""
                },
                    {
                    "infinite": "",
                    "inf_delay": "",
                    "inf_duration": "",
                    "animate": ["fadeIn"],
                    "delay": ["2000"],
                    "height": "23",
                    "img": "./image/page8/textImg1.png",
                    "rotate": "",
                    "width": "238",
                    "x": "256",
                    "y": "1007",
                    "z_order": "1",
                    "duration": ["2000"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_2",
                    "line_spacing": ""
                },
                    {
                    "infinite": "",
                    "inf_delay": "",
                    "inf_duration": "",
                    "animate": ["fadeIn"],
                    "delay": ["2500"],
                    "height": "64",
                    "img": "./image/page8/textImg2.png",
                    "rotate": "",
                    "width": "267",
                    "x": "241",
                    "y": "1058",
                    "z_order": "1",
                    "duration": ["2000"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_3",
                    "line_spacing": ""
                },
                    {
                    "infinite": "",
                    "inf_delay": "",
                    "inf_duration": "",
                    "animate": ["fadeIn"],
                    "delay": ["2500"],
                    "height": "86",
                    "img": "./image/page8/lineImg1.png",
                    "rotate": "",
                    "width": "371",
                    "x": "190",
                    "y": "1046",
                    "z_order": "1",
                    "duration": ["2000"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_4",
                    "line_spacing": ""
                },
                    {
                    "animate": ["fadeInDown"],
                    "img": "./image/page8/peopleImg1.jpg",
                    "delay": ["2500"],
                    "rotate": 0,
                    "x": "61",
                    "y": "77",
                    "width": "314",
                    "height": "438",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "314",
                        "height": "438"
                    },
                    "z_order": 1,
                    "id": 9633,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                },
                    {
                    "animate": ["fadeInLeft"],
                    "img": "./image/page8/peopleImg2.jpg",
                    "delay": ["2000"],
                    "rotate": 0,
                    "x": "375",
                    "y": "77",
                    "width": "314",
                    "height": "438",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "314",
                        "height": "438"
                    },
                    "z_order": 1,
                    "id": 9634,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                },
                    {
                    "animate": ["fadeInRight"],
                    "img": "./image/page8/peopleImg3.jpg",
                    "delay": ["100"],
                    "rotate": 0,
                    "x": "61",
                    "y": "515",
                    "width": "314",
                    "height": "438",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "314",
                        "height": "438"
                    },
                    "z_order": 1,
                    "id": 9635,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                },
                    {
                    "animate": ["fadeInDown"],
                    "img": "./image/page8/peopleImg4.jpg",
                    "delay": ["1500"],
                    "rotate": 0,
                    "x": "375",
                    "y": "515",
                    "width": "314",
                    "height": "438",
                    "mask": {
                        "img": "./image/peopleImgMask.png",
                        "width": "314",
                        "height": "438"
                    },
                    "z_order": 1,
                    "id": 9636,
                    "type": "image",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0,
                    "fit_full_screen": 0
                }
                ]
            }
        },
            {
            "layout": {
                "background": "../static/images/pageBg.jpg",
                "elements": [
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rotateInDownRight"],
                    "delay": ["500ms"],
                    "height": "225",
                    "img": "../static/images/page9/elementImg1.png",
                    "rotate": "",
                    "width": "149",
                    "x": "64",
                    "y": "162",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_0",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeInUp"],
                    "delay": ["500ms"],
                    "height": "151",
                    "img": "../static/images/page9/elementImg2.png",
                    "rotate": "",
                    "width": "197",
                    "x": "202",
                    "y": "73",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_1",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["rotateInDownLeft"],
                    "delay": ["500ms"],
                    "height": "232",
                        "img": "../static/images/page9/elementImg3.png",
                    "rotate": "",
                    "width": "256",
                    "x": "420",
                    "y": "75",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_2",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["500ms"],
                    "height": "207",
                    "img": "../static/images/page9/elementImg4.png",
                    "rotate": "",
                    "width": "271",
                    "x": "91",
                    "y": "759",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_3",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["500ms"],
                    "height": "51",
                    "img": "../static/images/page9/elementImg5.png",
                    "rotate": "",
                    "width": "83",
                    "x": "387",
                    "y": "918",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_4",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeInDown"],
                    "delay": ["500ms"],
                    "height": "178",
                    "img": "../static/images/page9/elementImg6.png",
                    "rotate": "",
                    "width": "182",
                    "x": "481",
                    "y": "779",
                    "z_order": "1",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_5",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["100ms"],
                    "height": "817",
                    "img": "../static/images/page9/pageBg.png",
                    "rotate": "",
                    "width": "561",
                    "x": "95",
                    "y": "133",
                    "z_order": "2",
                    "duration": ["1000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_6",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["100ms"],
                    "height": "817",
                    "img": "../static/images/page9/pageBgBorder.png",
                    "rotate": "",
                    "width": "561",
                    "x": "95",
                    "y": "133",
                    "z_order": "3",
                    "duration": ["1000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_7",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["fadeIn"],
                    "delay": ["500ms"],
                    "height": "80",
                    "img": "./image/page9/textImg1.png",
                    "rotate": "",
                    "width": "354",
                    "x": "208",
                    "y": "219",
                    "z_order": "3",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_8",
                    "line_spacing": null
                },
                    {
                    "infinite": "",
                    "inf_delay": "ms",
                    "inf_duration": "ms",
                    "animate": ["zoomIn"],
                    "delay": ["500ms"],
                    "height": "4",
                    "img": "./image/page9/lineImg1.png",
                    "rotate": "",
                    "width": "70",
                    "x": "340",
                    "y": "312",
                    "z_order": "3",
                    "duration": ["2000ms"],
                    "is_down": "0",
                    "is_scale": "0",
                    "id": "ele_9",
                    "line_spacing": null
                },
                    {
                    "animate": ["fadeIn"],
                    "img": "./image/page1/dateImg.png",
                    "delay": ["1500"],
                    "rotate": "0",
                    "x": "191",
                    "y": "743",
                    "width": "369",
                    "height": "31",
                    "z_order": "3",
                    "id": 13137,
                    "type": "text",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "text_type": "time",
                    "edit_btn_position": 0
                },
                    {
                    "animate": ["fadeIn"],
                    "img": "./image/page1/addressImg.png",
                    "delay": ["2000"],
                    "rotate": "0",
                    "x": "137",
                    "y": "784",
                    "width": "476",
                    "height": "70",
                    "z_order": "3",
                    "id": 13138,
                    "type": "text",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "text_type": "location",
                    "edit_btn_position": 0
                },
                    {
                    "animate": ["fadeIn"],
                    "delay": ["1000"],
                    "x": "120",
                    "y": "362",
                    "width": "510",
                    "height": "349",
                    "z_order": "3",
                    "id": 1753,
                    "type": "map",
                    "is_scale": 0,
                    "is_down": 0,
                    "duration": ["2000ms"],
                    "infinite": "",
                    "inf_duration": "",
                    "inf_delay": "",
                    "edit_btn_position": 0
                }
                ],
                "layTemplate": "layTemplate_feedback",
                "attendButton": {"textColor": "#ffffff", "fillColor": "#2d86af", "boxColor": "#2d86af"}
            }
        }
        ],
    "music": {
        "audio": "../static/audio/BGM.mp3",
        "img": "../static/images/audio/music.png",
        "close_img": "../static/images/audio/music.png"
    },
    "page_icon": "../static/images/upArrow.png",
    "background_path": "../static/images/BGPath.jpg",
    "theme_background": "../static/images/BGPath.jpg"
}